networks:
    labtrack_network:
        name: labtrack_network

services:
    labtrack_nginx:
        image: nginx:alpine
        container_name: labtrack_nginx
        restart: always
        env_file: ".env"
        ports:
            - "${HTTP_PORT}:80"
        networks:
            - labtrack_network
        volumes:
            - ".:/var/www/html:rw"
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - labtrack_php
            - labtrack_db

    labtrack_php:
        container_name: labtrack_php
        restart: always
        env_file: ".env"
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        networks:
            - labtrack_network
        volumes:
            - ".:/var/www/html:rw"
            - "../alxarafe:/var/www/alxarafe:rw"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    labtrack_db:
        image: mariadb:10.11
        container_name: labtrack_db
        restart: always
        env_file: ".env"
        ports:
            - "${MARIADB_PORT}:3306"
        environment:
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - labtrack_network
        volumes:
            - "labtrack_db_data:/var/lib/mysql"

    labtrack_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: labtrack_phpmyadmin
        restart: always
        env_file: ".env"
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            - PMA_HOST=labtrack_db
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - labtrack_network
        depends_on:
            - labtrack_db

volumes:
    labtrack_db_data:
